MVC/Controllers/AddUpdateController.cs
using System;
using System.Linq;
using MVC.Models;

namespace MVC.Controllers
{
    public class AddUpdateController : Controller
    {
        private MVCContext context = new MVCContext();
        public ActionResult AddUpdate(Int32? id)
        {
            if (id == null)
            {
                ViewBag.TiTle = "Add";
                var customers = new Customer();
                return View("~/Views/Edit/Edit.cshtml", customers);
            }
            else
            {
                ViewBag.TiTle = "Update";
                Int64 customerID = Convert.ToInt64(id);
                var customers = context.Customers.Where(t => t.CustomerID == customerID).OrderBy(o => o.FirstName).ThenBy(p => p.LastName).SingleOrDefault();
                return View("~/Views/Edit/Edit.cshtml", customers);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Customer obj)
        {
            if (ModelState.IsValid)
            {
                if (Convert.ToInt64(obj.CustomerID) > 0)
                {
                    context.Customers.Attach(obj);
                    context.Configuration.ValidateOnSaveEnabled = false;

                    context.Entry(obj).Property(u => u.FirstName).IsModified = true;
                    context.Entry(obj).Property(u => u.LastName).IsModified = true;
                    context.Entry(obj).Property(u => u.BirthDate).IsModified = true;
                    context.Entry(obj).Property(u => u.Email).IsModified = true;
                    context.Entry(obj).Property(u => u.Address).IsModified = true;

                    if (context.SaveChanges() > 0)
                    {
                        context.Configuration.ValidateOnSaveEnabled = true;
                        TempData["Message"] = "Updated Successfully";
                    }
                    else
                    {
                        TempData["Message"] = "Error whle updating";
                    }
                }
                else
                {
                    context.Customers.Add(obj);
                    if (context.SaveChanges() > 0)
                    {
                        var customerID = obj.CustomerID;
                        TempData["Message"] = "Saved Successfully";
                    }
                    else
                    {
                        TempData["Message"] = "Error whle saving";
                    }
                }
                return RedirectToAction("List", "List");
            }

            return View("~/Views/Edit/Edit.cshtml", obj);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC/Controllers/ListController.cs
using System;
using System.Linq;
using System.Net;
using MVC.Models;

namespace MVC.Controllers
{
    public class ListController : Controller
    {
        private MVCContext context = new MVCContext();
        public ActionResult List()
        {   
            var customers = context.Customers.OrderBy(o => o.FirstName).ThenBy(p => p.LastName).ToList();
            if (customers == null)
            {
                return HttpNotFound();
            }
            return View(customers);
        }
            
        public ActionResult Delete(Int64? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Int64 customerID = Convert.ToInt64(id);
            Customer customers = context.Customers.Where(m => m.CustomerID == customerID).SingleOrDefault();
            if (customers == null)
            {
                return HttpNotFound();
            }
            context.Customers.Remove(customers);
            if (context.SaveChanges() > 0)
            {
                TempData["Message"] = "Deleted Successfully";
                return RedirectToAction("List");
            }
            else
            {
                TempData["Message"] = "Error while deleting";
                return HttpNotFound();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC/Views/List/List.cshtml
@model List<MVC.Models.Customer>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List</h2>
<p>
    @Html.ActionLink("Add Customer", "AddUpdate", "AddUpdate")
</p>
<div class="table-responsive @(Model.Count > 0 ? "show" : "hidden")">
    <table class="table table-bordered">
        <tr class="bg-primary">
            <th>First Name
            </th>
            <th>Last Name
            </th>
            <th>Birth Date
            </th>
            <th>Email
            </th>
            <th>Address
            </th>
            <th>Edit | Delete
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @String.Format("{0:dd/MM/yyyy}", item.BirthDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.ActionLink("Edit", "AddUpdate", "AddUpdate", new { id = item.CustomerID }, null) |
                @Html.ActionLink("Delete", "Delete", new { id = item.CustomerID }, new { onclick = string.Format("return confirm('Are you sure you want to delete {0}?');", item.FirstName + " " + item.LastName) })
                </td>
            </tr>
        }

        @if (TempData["Message"] != null)
        {
            <script type="text/javascript">
                alert('@TempData["Message"]');
            </script>
        }
    </table>
</div>
<div class="@(Model.Count > 0 ? "hidden" : "show alert alert-danger fade in")">
    <strong>Sorry! </strong>No Record(s) found.
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#aSample').parent().addClass('active');
    });
</script>