MVC/Controllers/WCFController.cs
namespace MVC.Controllers
{
    public class WCFController : Controller
    {
        public ActionResult WCF()
        {
            ////  (1) Consume WebService from WebRequest
            //WebRequest req = WebRequest.Create(@"http://localhost:57840/CustomerService.svc/Customer/0");
            //req.Method = "GET";
            //req.ContentType = @"application/json; charset=utf-8";
            //HttpWebResponse response = (HttpWebResponse)req.GetResponse();
            //string jsonResponse = string.Empty;
            //List<Models.Customer> lst = new List<Models.Customer>();

            //using (StreamReader sr = new StreamReader(response.GetResponseStream()))
            //{
            //    jsonResponse = sr.ReadToEnd();
            //    lst = JsonConvert.DeserializeObject<List<Models.Customer>>(jsonResponse);
            //    //var lst = JsonConvert.DeserializeObject(jsonResponse);
            //    return View(lst);
            //}

            ////  (2) Consume WebService from WebClient
            //WebClient proxy = new WebClient();
            //string serviceURL = string.Format("http://localhost:57840/CustomerService.svc/Customer/0");
            //byte[] data = proxy.DownloadData(serviceURL);
            //Stream stream = new MemoryStream(data);
            //DataContractJsonSerializer obj = new DataContractJsonSerializer(typeof(List<Models.Customer>));
            //List<Models.Customer> lst = obj.ReadObject(stream) as List<Models.Customer>;
            //return View(lst);

            return View();
        }
    }
}

MVC/Controllers/WebAPIController.cs
namespace MVC.Controllers
{
    public class WebAPIController : Controller
    {
        public ActionResult WebAPI()
        {
            return View();
        }
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <title>@ViewBag.Title - Sample Application</title>
    
    @System.Web.Optimization.Styles.Render("~/Content/css")
    @System.Web.Optimization.Scripts.Render("~/bundles/modernizr")
    @System.Web.Optimization.Scripts.Render("~/bundles/jquery")
    @System.Web.Optimization.Scripts.Render("~/bundles/jqueryval")
    @System.Web.Optimization.Scripts.Render("~/bundles/DeveloperJs")
    @System.Web.Optimization.Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "List", "List", new { area = "" }, new { @id = "aHome", @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Sample Application", "List", "List", new { area = "" }, new { @id = "aSample" })</li>
                    <li>@Html.ActionLink("Consume WebAPI", "WebAPI", "WebAPI", new { area = "" }, new { @id = "aConsumeWebAPI" })</li>
                    <li>@Html.ActionLink("Consume WCF", "WCF", "WCF", new { area = "" }, new { @id = "aConsumeWCF" })</li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - Search Application</p>*@
        </footer>
    </div>
    <script type="text/javascript">
        $('.nav li.active').removeClass('active');
    </script>
</body>
</html>